In [1]:
import numpy as np
import pandas as pd

In [2]:
num1=np.array([1,2,3,4,5])
print("numpy array :", num1)

numpy array : [1 2 3 4 5]


In [4]:
print("this is shape of num1->",np.shape(num1))

this is shape of num1 (5,)


In [10]:
num2=pd.Series([1,2,3,4,5])
print("this is series in pandas",num2)

this is series in pandas 0    1
1    2
2    3
3    4
4    5
dtype: int64


In [13]:
num3=np.array([1,2,3,4,5,6,7,8,9,10])
print("this is one dimensonal array with ten element->",num3)

this is one dimensonal array with ten element-> [ 1  2  3  4  5  6  7  8  9 10]


In [15]:
num4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("this is multi-dimensonal array in numpy->",num4)

this is multi-dimensonal array in numpy-> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
num5=np.zeros([4,5])
print("this is zeros in numpy->", num5)

this is zeros in numpy-> [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
num6=np.ones([5,4])
print("this is ones in numpy->", num6)

this is ones in numpy-> [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
